// client/src/components/Messages.vue
<script setup lang="ts">


    import { useMessages } from '../models/messages';

    const messages = useMessages();

</script>

<template>
    <div>
        <div v-for=" (x, i) in messages.notifications" :class="`notification is-${x.type}`">
            <button class="delete" @click="messages.close(i)" ></button>
            {{ x.message }}
        </div>
    </div>
</template>


<style scoped>

</style>

// react-app/src/models/messages.ts
import { useState } from "react";



export default function useMessages() {

    const [notifications, setNotifications] = useState<Notification[]>([
        { type: "success", message: "Success message" },
    ]);
  
    return {
        notifications,
        add(notification: Notification) {
            setNotifications([...notifications, notification]);
        },
        close(index: number) {
            setNotifications(notifications.filter((_, i) => i !== index));
        }
    }
}

export interface Notification {
    type: 'success' | 'danger' | 'info' | 'warning';
    message: string;
}
